# 개발 환경에서는 로컬 데이터 사용
use_azure=false
# 운영 환경에서 Azure 사용 시
connection_string = "DefaultEndpointsProtocol=https;AccountName=yourstorageaccount;AccountKey=yourkey;EndpointSuffix=core.windows.net"
container_name = "performance-data"